=== caiusCitiriga/nrg-cli/src/config/cli-conf.schema.json
{
    "$id": "http://example.com/example.json",
    "type": "object",
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "srcFolder": {
            "$id": "/properties/srcFolder",
            "type": "string",
            "title": "The Srcfolder Schema ",
            "default": "",
            "examples": [
                "src"
            ]
        },
        "defaultExt": {
            "$id": "/properties/defaultExt",
            "type": "string",
            "title": "The Defaultext Schema ",
            "default": "",
            "examples": [
                "ts",
                "js"
            ]
        },
        "additionalTypes": {
            "$id": "/properties/additionalTypes",
            "type": "array",
            "items": {
                "$id": "/properties/additionalTypes/items",
                "type": "object",
                "properties": {
                    "name": {
                        "$id": "/properties/additionalTypes/items/properties/name",
                        "type": "string",
                        "title": "The Name Schema ",
                        "default": "",
                        "examples": [
                            ""
                        ]
                    },
                    "plural": {
                        "$id": "/properties/additionalTypes/items/properties/plural",
                        "type": "string",
                        "title": "The Plural Schema ",
                        "default": "",
                        "examples": [
                            ""
                        ]
                    }
                }
            }
        },
        "customFileTemplates": {
            "$id": "/properties/customFileTemplates",
            "type": "array",
            "items": {
                "$id": "/properties/customFileTemplates/items",
                "type": "object",
                "properties": {
                    "itemName": {
                        "$id": "/properties/customFileTemplates/items/properties/itemName",
                        "type": "string",
                        "title": "The Itemname Schema ",
                        "default": "",
                        "examples": [
                            "dto",
                            "enum",
                            "model",
                            "const",
                            "custom",
                            "entity",
                            "interface"
                        ]
                    },
                    "template": {
                        "$id": "/properties/customFileTemplates/items/properties/template",
                        "type": "string",
                        "title": "The Template Schema ",
                        "default": "",
                        "examples": [
                            "export class #classname# {\n\n}\n"
                        ]
                    }
                }
            }
        },
        "dotnetInterfaceStyle": {
            "$id": "/properties/dotnetInterfaceStyle",
            "type": "boolean",
            "title": "The Dotnetinterfacestyle Schema ",
            "default": false,
            "examples": [
                true,
                false
            ]
        }
    }
}

=== caiusCitiriga/nrg-cli/src/config/energy.cli.default.json
{
    "srcFolder": "src",
    "defaultExt": "ts",
    "additionalTypes": [
        {
            "name": "test",
            "plural": "tests"
        }
    ],
    "customFileTemplates": [
        {
            "itemName": "dto",
            "template": "export class #classname# {\n\n}\n"
        },
        {
            "itemName": "test",
            "template": "export class #classname# {\n\n}\n"
        }
    ],
    "dotnetInterfaceStyle": false
}
